(define *themes* (make-hash-table))
(define *current-theme* #f)

(define (define-theme name palette roles)
  (hash-table-set!
   *themes*
   name
   (list palette roles)))

(defcommand (activate-theme input)
  "Switch to the named theme."
  (interactive (minibuffer-read "Theme: "))
  (let* ((sym   (if (string? input) (string->symbol input) input))
         (theme (hash-table-ref *themes* sym))
         (palette (car theme))
         (roles   (cadr theme)))
    (%clear-palette!)
    (%clear-roles!)

    (for-each (lambda (p)
                (%set-palette! (car p) (cdr p)))
              palette)

    (for-each (lambda (r)
                (%set-role! (car r) (cdr r)))
              roles)

    (set! *current-theme* sym)
    (%update-icon-colors!)))

(define-theme
 'catppuccin-mocha

 ;; palette
 '((bg-0      . "#1e1e2e")
   (bg-1      . "#181825")
   (bg-2      . "#11111b")
   (fg-0      . "#313244")
   (fg-1      . "#45475a")
   (fg-2      . "#585b70")
   (accent-0  . "#6c7086")
   (accent-1  . "#7f849c")
   (accent-2  . "#9399b2")
   (text-0    . "#cdd6f4")
   (text-1    . "#bac2de")
   (text-2    . "#a6adc8")
   (select    . "#9399b240")
   (lavender  . "#b4befe")
   (blue      . "#89b4fa")
   (sapphire  . "#74c7ec")
   (sky       . "#89dceb")
   (teal      . "#94e2d5")
   (green     . "#a6e3a1")
   (yellow    . "#f9e2af")
   (peach     . "#fab387")
   (maroon    . "#eba0ac")
   (red       . "#f38ba8")
   (mauve     . "#cba6f7")
   (pink      . "#f5c2e7")
   (flamingo  . "#f2cdcd")
   (rosewater . "#f5e0dc"))

 ;; roles
 '((ui.bg             . bg-1)
   (pane.bg           . bg-0)
   (border.active     . mauve)
   (border.inactive   . fg-0)
   (border.bell       . yellow)
   (tab.bar           . bg-2)
   (tab.active        . bg-0)
   (tab.hover         . bg-0)
   (tab.inactive      . bg-2)
   (text.primary      . text-0)
   (text.faded        . fg-2)
   (text.key          . green)
   (text.command      . blue)
   (text.prefix       . mauve)
   (selection         . select)
   (bar.bg            . fg-0)
   (mode.normal       . lavender)
   (mode.insert       . green)
   (mode.replace      . red)
   (mode.select       . yellow)
   (mode.command      . peach)
   (mode.pending      . flamingo)
   (mode.minibuffer   . sky)
   (mode.help         . teal)
   (label.normal      . fg-0)
   (label.insert      . fg-0)
   (label.replace     . fg-0)
   (label.select      . fg-0)
   (label.command     . fg-0)
   (label.pending     . fg-0)
   (label.minibuffer  . fg-0)
   (label.help        . fg-0)
   (cursor.normal     . rosewater)
   (cursor.insert     . rosewater)
   (cursor.replace    . rosewater)
   (cursor.select     . rosewater)
   (cursor.command    . rosewater)
   (cursor.pending    . rosewater)
   (cursor.minibuffer . rosewater)
   (cursor.help       . rosewater)
   (macro.indicator   . red)
   (macro.bg          . fg-2)
   (hl.keyword        . (:color mauve))
   (hl.string         . (:color green))
   (hl.comment        . (:color accent-0 :font buf-italic))
   (hl.number         . (:color peach))
   (hl.constant       . (:color peach))
   (hl.function       . (:color blue))
   (hl.builtin        . (:color sky))
   (hl.operator       . (:color text-0))
   (hl.bracket        . (:color accent-0))))

(define-theme
 'catppuccin-macchiato

 ;; palette
 '((bg-0      . "#24273a")
   (bg-1      . "#1e2030")
   (bg-2      . "#181926")
   (fg-0      . "#363a4f")
   (fg-1      . "#494d64")
   (fg-2      . "#5b6078")
   (accent-0  . "#6e738d")
   (accent-1  . "#8087a2")
   (accent-2  . "#939ab7")
   (text-0    . "#cad3f5")
   (text-1    . "#b8c0e0")
   (text-2    . "#a5adcb")
   (select    . "#939ab740")
   (lavender  . "#b7bdf8")
   (blue      . "#8aadf4")
   (sapphire  . "#7dc4e4")
   (sky       . "#91d7e3")
   (teal      . "#8bd5ca")
   (green     . "#a6da95")
   (yellow    . "#eed49f")
   (peach     . "#f5a97f")
   (maroon    . "#ee99a0")
   (red       . "#ed8796")
   (mauve     . "#c6a0f6")
   (pink      . "#f5bde6")
   (flamingo  . "#f0c6c6")
   (rosewater . "#f4dbd6"))

 ;; roles
 '((ui.bg             . bg-1)
   (pane.bg           . bg-0)
   (border.active     . mauve)
   (border.inactive   . fg-0)
   (border.bell       . yellow)
   (tab.bar           . bg-2)
   (tab.active        . bg-0)
   (tab.hover         . bg-0)
   (tab.inactive      . bg-2)
   (text.primary      . text-0)
   (text.faded        . fg-2)
   (text.key          . green)
   (text.command      . blue)
   (text.prefix       . mauve)
   (selection         . select)
   (bar.bg            . fg-0)
   (mode.normal       . lavender)
   (mode.insert       . green)
   (mode.replace      . red)
   (mode.select       . yellow)
   (mode.command      . peach)
   (mode.pending      . flamingo)
   (mode.minibuffer   . sky)
   (mode.help         . teal)
   (label.normal      . fg-0)
   (label.insert      . fg-0)
   (label.replace     . fg-0)
   (label.select      . fg-0)
   (label.command     . fg-0)
   (label.pending     . fg-0)
   (label.minibuffer  . fg-0)
   (label.help        . fg-0)
   (cursor.normal     . rosewater)
   (cursor.insert     . rosewater)
   (cursor.replace    . rosewater)
   (cursor.select     . rosewater)
   (cursor.command    . rosewater)
   (cursor.pending    . rosewater)
   (cursor.minibuffer . rosewater)
   (cursor.help       . rosewater)
   (macro.indicator   . red)
   (macro.bg          . fg-2)
   (hl.keyword        . (:color mauve))
   (hl.string         . (:color green))
   (hl.comment        . (:color accent-0 :font buf-italic))
   (hl.number         . (:color peach))
   (hl.constant       . (:color peach))
   (hl.function       . (:color blue))
   (hl.builtin        . (:color sky))
   (hl.operator       . (:color text-0))
   (hl.bracket        . (:color accent-0))))

(define-theme
 'catppuccin-latte

 ;; palette
 '((bg-0      . "#eff1f5")
   (bg-1      . "#e6e9ef")
   (bg-2      . "#dce0e8")
   (fg-0      . "#ccd0da")
   (fg-1      . "#bcc0cc")
   (fg-2      . "#acb0be")
   (accent-0  . "#9ca0b0")
   (accent-1  . "#8c8fa1")
   (accent-2  . "#7c7f93")
   (text-0    . "#4c4f69")
   (text-1    . "#5c5f77")
   (text-2    . "#6c6f85")
   (select    . "#7c7f9340")
   (lavender  . "#7287fd")
   (blue      . "#1e66f5")
   (sapphire  . "#209fb5")
   (sky       . "#04a5e5")
   (teal      . "#179299")
   (green     . "#40a02b")
   (yellow    . "#df8e1d")
   (peach     . "#fe640b")
   (maroon    . "#e64553")
   (red       . "#d20f39")
   (mauve     . "#8839ef")
   (pink      . "#ea76cb")
   (flamingo  . "#dd7878")
   (rosewater . "#dc8a78"))

 ;; roles
 '((ui.bg             . bg-1)
   (pane.bg           . bg-0)
   (border.active     . mauve)
   (border.inactive   . fg-0)
   (border.bell       . yellow)
   (tab.bar           . bg-2)
   (tab.active        . bg-0)
   (tab.hover         . bg-0)
   (tab.inactive      . bg-2)
   (text.primary      . text-0)
   (text.faded        . fg-2)
   (text.key          . green)
   (text.command      . blue)
   (text.prefix       . mauve)
   (selection         . select)
   (bar.bg            . bg-2)
   (mode.normal       . lavender)
   (mode.insert       . green)
   (mode.replace      . red)
   (mode.select       . yellow)
   (mode.command      . peach)
   (mode.pending      . flamingo)
   (mode.minibuffer   . sky)
   (mode.help         . teal)
   (label.normal      . bg-0)
   (label.insert      . bg-0)
   (label.replace     . bg-0)
   (label.select      . bg-0)
   (label.command     . bg-0)
   (label.pending     . bg-0)
   (label.minibuffer  . bg-0)
   (label.help        . bg-0)
   (cursor.normal     . rosewater)
   (cursor.insert     . rosewater)
   (cursor.replace    . rosewater)
   (cursor.select     . rosewater)
   (cursor.command    . rosewater)
   (cursor.pending    . rosewater)
   (cursor.minibuffer . rosewater)
   (cursor.help       . rosewater)
   (macro.indicator   . red)
   (macro.bg          . fg-2)
   (hl.keyword        . (:color mauve))
   (hl.string         . (:color green))
   (hl.comment        . (:color accent-0 :font buf-italic))
   (hl.number         . (:color peach))
   (hl.constant       . (:color peach))
   (hl.function       . (:color blue))
   (hl.builtin        . (:color sky))
   (hl.operator       . (:color text-0))
   (hl.bracket        . (:color accent-0))))

(activate-theme 'catppuccin-macchiato)

