;;; init.scm - Editor initialization and keybindings

(import (editor command) (editor mode) (editor icon)
        (editor built-in) (editor evil) (editor theme)
        (editor minibuffer) (editor which-key))

;; System/UI bindings in global-keymap (inherited by all mode keymaps via parent)
(set-key! global-keymap "ESC" 'evil-normal)
(set-key! global-keymap "C-[" 'evil-normal)
(set-key! global-keymap "C-q" 'quit)
(set-key! global-keymap "C-e" 'eval-expression)
(set-key! global-keymap "C-TAB" 'tab-next)
(set-key! global-keymap "C-S-TAB" 'tab-prev)
(set-key! global-keymap "C-w" 'pane-close)
(set-key! global-keymap "C-s" 'save-buffer)
(set-key! global-keymap "C-S-s" 'save-buffer-as)
(set-key! global-keymap "M-0" 'reset-global-scale)
(set-key! global-keymap "h" 'evil-motion-h)
(set-key! global-keymap "j" 'evil-motion-j)
(set-key! global-keymap "k" 'evil-motion-k)
(set-key! global-keymap "l" 'evil-motion-l)
(set-key! global-keymap "LEFT" 'evil-motion-h)
(set-key! global-keymap "DOWN" 'evil-motion-j)
(set-key! global-keymap "UP" 'evil-motion-k)
(set-key! global-keymap "RIGHT" 'evil-motion-l)
(set-key! global-keymap "M-=" 'increase-global-scale)
(set-key! global-keymap "M--" 'decrease-global-scale)
(set-key! global-keymap "C-0" 'reset-buffer-scale)
(set-key! global-keymap "C-=" 'increase-buffer-scale)
(set-key! global-keymap "C--" 'decrease-buffer-scale)
(set-key! global-keymap "C-h" 'pane-navigate-left)
(set-key! global-keymap "C-j" 'pane-navigate-down)
(set-key! global-keymap "C-k" 'pane-navigate-up)
(set-key! global-keymap "C-l" 'pane-navigate-right)
(set-key! global-keymap "C-LEFT" 'pane-navigate-left)
(set-key! global-keymap "C-DOWN" 'pane-navigate-down)
(set-key! global-keymap "C-UP" 'pane-navigate-up)
(set-key! global-keymap "C-RIGHT" 'pane-navigate-right)
(set-key! global-keymap "C-S-h" 'pane-v-split-decrease)
(set-key! global-keymap "C-S-j" 'pane-h-split-increase)
(set-key! global-keymap "C-S-k" 'pane-h-split-decrease)
(set-key! global-keymap "C-S-l" 'pane-v-split-increase)
(set-key! global-keymap "C-S-LEFT" 'pane-v-split-decrease)
(set-key! global-keymap "C-S-DOWN" 'pane-h-split-increase)
(set-key! global-keymap "C-S-UP" 'pane-h-split-decrease)
(set-key! global-keymap "C-S-RIGHT" 'pane-v-split-increase)
(set-key! global-keymap "SPC f o" 'open-file)
(define buffer-map (make-keymap))
(%set-keymap-name! buffer-map "buffer")
(set-key! buffer-map "n" 'buffer-new)
(set-key! buffer-map "r" 'buffer-rename)
(set-key! buffer-map "c" 'buffer-close)
(set-key! buffer-map "s" 'switch-to-buffer)
(bind-prefix! global-keymap "SPC b" buffer-map)
(define help-map (make-keymap))
(%set-keymap-name! help-map "help")
(set-key! help-map "f" 'describe-function)
(set-key! help-map "k" 'describe-key)
(set-key! help-map "w" 'which-key-toggle)
(bind-prefix! global-keymap "SPC h" help-map)
(define line-numbers-map (make-keymap))
(%set-keymap-name! line-numbers-map "line-numbers")
(set-key! line-numbers-map "n" 'toggle-line-numbers)
(set-key! line-numbers-map "r" 'toggle-relative-line-numbers)
(set-key! line-numbers-map "v" 'toggle-visual-line-numbers)
(bind-prefix! global-keymap "SPC l" line-numbers-map)
(define split-map (make-keymap))
(%set-keymap-name! split-map "split")
(set-key! split-map "h" 'split-horizontal)
(set-key! split-map "v" 'split-vertical)
(bind-prefix! global-keymap "SPC s" split-map)
(set-key! global-keymap "SPC t n" 'tab-new)

(set-key! global-keymap "M-x" 'execute-extended-command)
(set-key! global-keymap "M-:" 'eval-expression)

;; Click: exit any visual select mode, then move point to clicked position.
(%set-mouse-click-handler!
  (lambda (button buf-pos clicks)
    (when (= button 1)
      (when (%buffer-has-minor-mode? 'evil-select-mode)
        (evil-normal))
      (point-set! buf-pos))))

;; Drag: on first motion enter visual-char mode anchored at the click position
;; (the click handler already moved point there), then track cursor.
;; In evil buffers this activates evil-select-mode; in others point just follows.
(%set-mouse-drag-handler!
  (lambda (current-pos start-pos)
    (when (and (not (%buffer-has-minor-mode? 'evil-select-mode))
               (or (%buffer-has-minor-mode? 'evil-normal-mode)
                   (%buffer-has-minor-mode? 'evil-insert-mode)
                   (%buffer-has-minor-mode? 'evil-replace-mode)))
      ;; Point is at start-pos (set by click handler); evil-select anchors
      ;; mark < there, then enables evil-select-mode with SELECT_REGULAR.
      (evil-select))
    (point-set! current-pos)))

;; Splash keymap: minimal set of commands available when no panes/tabs are open.
;; Intentionally excludes cursor motion and editing commands.
(define splash-map (make-keymap))
(%set-keymap-name! splash-map "splash")
(bind-prefix! splash-map "SPC b" buffer-map)
(bind-prefix! splash-map "SPC h" help-map)
(set-key! splash-map "SPC t n" 'tab-new)
(set-key! splash-map "M-x"     'execute-extended-command)
(set-key! splash-map "C-q"     'quit)
(set-key! splash-map "SPC f o" 'open-file)
(%set-splash-keymap! splash-map)

(reset-global-scale)
(message-clear)
