;;; init.scm - Editor initialization and keybindings

(import (editor command) (editor mode) (editor icon)
        (editor built-in) (editor evil) (editor theme)
        (editor minibuffer) (editor which-key))

;; System/UI bindings in global-keymap (inherited by all mode keymaps via parent)
(set-key! global-keymap "ESC" 'evil-normal)
(set-key! global-keymap "C-[" 'evil-normal)
(set-key! global-keymap "C-q" 'quit)
(set-key! global-keymap "C-e" 'eval-buffer)
(set-key! global-keymap "C-TAB" 'tab-next)
(set-key! global-keymap "C-S-TAB" 'tab-prev)
(set-key! global-keymap "C-w" 'pane-close)
(set-key! global-keymap "C-s" 'save-buffer)
(set-key! global-keymap "C-S-s" 'save-buffer-as)
(set-key! global-keymap "M-0" 'reset-global-scale)
(set-key! global-keymap "h" 'evil-motion-h)
(set-key! global-keymap "j" 'evil-motion-j)
(set-key! global-keymap "k" 'evil-motion-k)
(set-key! global-keymap "l" 'evil-motion-l)
(set-key! global-keymap "LEFT" 'evil-motion-h)
(set-key! global-keymap "DOWN" 'evil-motion-j)
(set-key! global-keymap "UP" 'evil-motion-k)
(set-key! global-keymap "RIGHT" 'evil-motion-l)
(set-key! global-keymap "M-=" 'increase-global-scale)
(set-key! global-keymap "M--" 'decrease-global-scale)
(set-key! global-keymap "C-0" 'reset-buffer-scale)
(set-key! global-keymap "C-=" 'increase-buffer-scale)
(set-key! global-keymap "C--" 'decrease-buffer-scale)
(set-key! global-keymap "C-h" 'pane-navigate-left)
(set-key! global-keymap "C-j" 'pane-navigate-down)
(set-key! global-keymap "C-k" 'pane-navigate-up)
(set-key! global-keymap "C-l" 'pane-navigate-right)
(set-key! global-keymap "C-LEFT" 'pane-navigate-left)
(set-key! global-keymap "C-DOWN" 'pane-navigate-down)
(set-key! global-keymap "C-UP" 'pane-navigate-up)
(set-key! global-keymap "C-RIGHT" 'pane-navigate-right)
(set-key! global-keymap "C-S-h" 'pane-v-split-decrease)
(set-key! global-keymap "C-S-j" 'pane-h-split-increase)
(set-key! global-keymap "C-S-k" 'pane-h-split-decrease)
(set-key! global-keymap "C-S-l" 'pane-v-split-increase)
(set-key! global-keymap "C-S-LEFT" 'pane-v-split-decrease)
(set-key! global-keymap "C-S-DOWN" 'pane-h-split-increase)
(set-key! global-keymap "C-S-UP" 'pane-h-split-decrease)
(set-key! global-keymap "C-S-RIGHT" 'pane-v-split-increase)
(define buffer-map (make-keymap))
(%set-keymap-name! buffer-map "buffer")
(set-key! buffer-map "n" 'buffer-new)
(set-key! buffer-map "r" 'buffer-rename)
(set-key! buffer-map "s" 'switch-to-buffer)
(bind-prefix! global-keymap "SPC b" buffer-map)
(define help-map (make-keymap))
(%set-keymap-name! help-map "help")
(set-key! help-map "f" 'describe-function)
(set-key! help-map "k" 'describe-key)
(set-key! help-map "w" 'which-key-toggle)
(bind-prefix! global-keymap "SPC h" help-map)
(set-key! global-keymap "SPC l n" 'toggle-line-numbers)
(set-key! global-keymap "SPC r n" 'toggle-relative-line-numbers)
(define split-map (make-keymap))
(%set-keymap-name! split-map "split")
(set-key! split-map "h" 'split-horizontal)
(set-key! split-map "v" 'split-vertical)
(bind-prefix! global-keymap "SPC s" split-map)
(set-key! global-keymap "SPC t n" 'tab-new)

(set-key! global-keymap "M-x" 'execute-extended-command)

(reset-global-scale)
(message-clear)
