(define *themes* (make-hash-table))
(define *current-theme* #f)

(define (define-theme name palette roles)
  (hash-table-set!
   *themes*
   name
   (list palette roles)))

(define (activate-theme name)
  (let* ((theme (hash-table-ref *themes* name))
         (palette (car theme))
         (roles   (cadr theme)))
    (%clear-palette!)
    (%clear-roles!)

    (for-each (lambda (p)
                (%set-palette! (car p) (cdr p)))
              palette)

    (for-each (lambda (r)
                (%set-role! (car r) (cdr r)))
              roles)

    (set! *current-theme* name)
    (%update-icon-colors!)))

(define-theme
 'catppuccin-mocha

 ;; palette
 '((bg-0      . "#1e1e2e")
   (bg-1      . "#181825")
   (bg-2      . "#11111b")
   (fg-0      . "#313244")
   (fg-1      . "#45475a")
   (fg-2      . "#585b70")
   (accent-0  . "#6c7086")
   (accent-1  . "#7f849c")
   (accent-2  . "#9399b2")
   (text-0    . "#cdd6f4")
   (text-1    . "#bac2de")
   (text-2    . "#a6adc8")
   (lavender  . "#b4befe")
   (blue      . "#89b4fa")
   (sapphire  . "#74c7ec")
   (sky       . "#89dceb")
   (teal      . "#94e2d5")
   (green     . "#a6e3a1")
   (yellow    . "#f9e2af")
   (peach     . "#fab387")
   (maroon    . "#eba0ac")
   (red       . "#f38ba8")
   (mauve     . "#cba6f7")
   (pink      . "#f5c2e7")
   (flamingo  . "#f2cdcd")
   (rosewater . "#f5e0dc"))

 ;; roles
 '((ui.bg         . bg-0)
   (bar.bg        . fg-1)
   (mode.normal   . blue)
   (mode.insert   . green)
   (label.normal  . bg-0)
   (label.insert  . bg-0)
   (tab.bar       . bg-1)
   (tab.active    . bg-0)
   (tab.hover     . bg-0)
   (tab.inactive  . bg-1)
   (text.primary  . text-0)
   (text.faded    . fg-2)
   (cursor.normal . rosewater)
   (cursor.insert . rosewater)))

(define-theme
 'catppuccin-macchiato

 ;; palette
 '((bg-0      . "#24273a")
   (bg-1      . "#1e2030")
   (bg-2      . "#181926")
   (fg-0      . "#363a4f")
   (fg-1      . "#494d64")
   (fg-2      . "#5b6078")
   (accent-0  . "#6e738d")
   (accent-1  . "#8087a2")
   (accent-2  . "#939ab7")
   (text-0    . "#cad3f5")
   (text-1    . "#b8c0e0")
   (text-2    . "#a5adcb")
   (lavender  . "#b7bdf8")
   (blue      . "#8aadf4")
   (sapphire  . "#7dc4e4")
   (sky       . "#91d7e3")
   (teal      . "#8bd5ca")
   (green     . "#a6da95")
   (yellow    . "#eed49f")
   (peach     . "#f5a97f")
   (maroon    . "#ee99a0")
   (red       . "#ed8796")
   (mauve     . "#c6a0f6")
   (pink      . "#f5bde6")
   (flamingo  . "#f0c6c6")
   (rosewater . "#f4dbd6"))

 ;; roles
 '((ui.bg         . bg-0)
   (bar.bg        . fg-1)
   (mode.normal   . blue)
   (mode.insert   . green)
   (label.normal  . bg-0)
   (label.insert  . bg-0)
   (tab.bar       . bg-1)
   (tab.active    . bg-0)
   (tab.hover     . bg-0)
   (tab.inactive  . bg-1)
   (text.primary  . text-0)
   (text.faded    . fg-2)
   (cursor.normal . rosewater)
   (cursor.insert . rosewater)))

(define-theme
 'catppuccin-latte

 ;; palette
 '((bg-0      . "#eff1f5")
   (bg-1      . "#e6e9ef")
   (bg-2      . "#dce0e8")
   (fg-0      . "#ccd0da")
   (fg-1      . "#bcc0cc")
   (fg-2      . "#acb0be")
   (accent-0  . "#9ca0b0")
   (accent-1  . "#8c8fa1")
   (accent-2  . "#7c7f93")
   (text-0    . "#4c4f69")
   (text-1    . "#5c5f77")
   (text-2    . "#6c6f85")
   (lavender  . "#7287fd")
   (blue      . "#1e66f5")
   (sapphire  . "#209fb5")
   (sky       . "#04a5e5")
   (teal      . "#179299")
   (green     . "#40a02b")
   (yellow    . "#df8e1d")
   (peach     . "#fe640b")
   (maroon    . "#e64553")
   (red       . "#d20f39")
   (mauve     . "#8839ef")
   (pink      . "#ea76cb")
   (flamingo  . "#dd7878")
   (rosewater . "#dc8a78"))

 ;; roles
 '((ui.bg         . bg-0)
   (bar.bg        . fg-1)
   (mode.normal   . blue)
   (mode.insert   . green)
   (label.normal  . bg-0)
   (label.insert  . bg-0)
   (tab.bar       . bg-1)
   (tab.active    . bg-0)
   (tab.hover     . bg-0)
   (tab.inactive  . bg-1)
   (text.primary  . text-0)
   (text.faded    . fg-2)
   (cursor.normal . rosewater)
   (cursor.insert . rosewater)))

(activate-theme 'catppuccin-macchiato)

